-- 漂浮字符
ttg.char("0", "singluar_ttg_0", 1.9)
ttg.char("1", "singluar_ttg_1", 1.8)
ttg.char("2", "singluar_ttg_2", 1.8)
ttg.char("3", "singluar_ttg_3", 1.8)
ttg.char("4", "singluar_ttg_4", 1.8)
ttg.char("5", "singluar_ttg_5", 1.8)
ttg.char("6", "singluar_ttg_6", 1.8)
ttg.char("7", "singluar_ttg_7", 1.8)
ttg.char("8", "singluar_ttg_8", 1.8)
ttg.char("9", "singluar_ttg_9", 1.8)
ttg.char("+", "singluar_ttg_+", 1.7)
ttg.char("-", "singluar_ttg_-", 1.7)