SL_CACHE["Refresh"] = Array()
Game().onEvent(EVENT.Game.Start, "Refresh", function()
    JassJapi["DzFrameSetUpdateCallbackByCode"](function()
        async.call(PlayerLocal(), function()
            SL_CACHE["Refresh"].forEach(function(_, call)
                promise(call)
            end)
        end)
    end)
end)